# Generated by Django 5.0.4 on 2024-04-13 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_alter_encuesta_preguntas_encuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuesta',
            name='preguntas_encuesta',
        ),
    ]
